<?php
namespace App\Facade;

class Helper
{
    /**
     * get upper case of string
     *
     * @param  string $str string need uppercase
     * @return string
     */
    public function toUpperCase($name)
    {
        return mb_strtoupper($name, 'UTF-8');
    }

    /**
     * @return array
     */
    public function getLocation()
    {
        return [
            'AEON MALL Hà Đông, Phố Hoàng Văn Thụ, Dương Nội, Hà Đông, Hà Nội',
            'Bana Hills Cable Station, Hòa Vang, Da Nang, Việt Nam',
            'Chợ Nguyễn Công Trứ, Nguyễn Công Trứ, Phố Huế, Hai Bà Trưng, Hà Nội',
            '68 Dương Đình Nghệs, Yên Hoà, Cầu Giấy, Hà Nội',
            'Ecopark, Khu đô thị Ecopark, Xuân Quan, Văn Giang, Hưng Yên',
            'Flamingo Đại Lải Resort, Lò Đúc, Đồng Xuân, Hai Bà Trưng, Hà Nội',
            'Golden palace, Đồng Me, Mễ Trì, Nam Từ Liêm, Hà Nội',
            '219 Hà Trì, Hà Đông, Hà Nội',
            'Indochina Plaza Hanoi Residences, Xuân Thủy, Dịch Vọng Hậu, Cầu Giấy, Hà Nội',
            'JW Marriott Hotel Hanoi, Đỗ Đức Dục, Road, Mễ Trì, Từ Liêm, Hà Nội',
            'Keangnam Landmark Tower 72, Phạm Hùng, Keangnam, Mễ Trì, Nam Từ Liêm, Hà Nội',
            'MobileCity Cầu Giấy, Đường Cầu Giấy, Dịch Vọng, Cầu Giấy, Hà Nội',
            'Nhà C2, Bách Khoa, Hai Bà Trưng, Hà Nội',
            'Ô Chợ Dừa, Đống Đa, Hà Nội',
            'Quán Ăn Ngon, Toà nhà 25T2, Nguyễn Thị Thập, Trung Hòa Nhân Chính, Trung Hoà, Cầu Giấy, Hà Nội',
            'Phạm Hùng, Cầu Giấy, Hà Nội',
            'Royal City, Ngõ 72 - Nguyễn Trãi, Khu đô thị Royal City, Thượng Đình, Thanh Xuân, Hà Nội',
            '7 Ngõ 122 - Láng, Thịnh Quang, Đống Đa, Hà Nội',
            'Hyundai Hà Nội, Trần Duy Hưng, Trung Hoà, Cầu Giấy, Hà Nội',
            'Udic Complex - N04, Hoàng Đạo Thúy, Trung Hòa Nhân Chính, Trung Hoà, Cầu Giấy, Hà Nội',
            'Vinhomes Royal City, Ngõ 72 - Nguyễn Trãi, Khu đô thị Royal City, Thượng Đình, Thanh Xuân, Hà Nội',
            'Xuân La, Tây Hồ, Hà Nội',
            '77 Yên Phúc, Phúc La, Hà Đông, Hà Nội',
            'WaterMark Hồ Tây, Đường Lạc Long Quân, Nghĩa Đô, Tây Hồ, Hà Nội',
            'ZARA, Bà Triệu, Lê Đại Hành, Hai Bà Trưng, Hà Nội',
            'Long Biên 1, Long Biên, Hà Nội',
            'Văn Điển, Đường Ngọc Hồi, Văn Điển, Thanh Trì, Hà Nội',
        ];
    }

    public function getEventName()
    {
        return [
            'Ngày hội siêu sale shopy',
            'Triển lãm oto VinFlat',
            'Ra mắt BePhone 2',
            'Ngày hội tri ân của BigE',
            'Marathon quanh Hồ gươm',
            'Tri ân khách hàng của Bititi',
            'Ssamsong tri ân khách hàng',
            'Ngày hội việc làm',
            'Sách hay ra mắt',
            'Thủy cung khai trương',
            'DH Bach Khoa Mừng ngày 20/11 ',
            'Kỉ niệm 20 năm thành lập',
            'Hội nghị biến đổi khí hậu',
            'Hội thảo chống cận thị',
            'Khai trương cửa hàng TekeTeke',
            'LowLand ra mắt hương vị mới',
            'Mở cửa khu vui chơi',
            'Giảm giá sách giáo khoa',
            'BQB giảm giá combo',
            'Tổ chức hội nghị phòng virus',
            'Tiêm vaccin covid20',
            'Occasion Blowout',
            'Everything New Attainment',
            'Six Tree',
            'Jade Moments',
            'Gold Hand',
            'Roads On The Go',
            'Open Social Experimenters',
            'Manor Get Planet',
            'Perfect All Experimenters',
            'Entertainment Your Sweet',
            'Gold Décor',
            'Reason Dots',
            'Castles Services',
            'Sunset Moment',
            'Oh How InStyle',
            'Silver Happen',
            'Castle Jumping Prep',
            'Oui Production Guardians',
            'Celebration Weddings',
            'Eventions Parade Festivities',
            'Jade Concourse Celebration',
            'Oui Red Guys',
            'Five Come Festivities',
            'Beyond Occasions',
            'Glamorous Logic',
            'PlanAhead Running Charms',
            // 'Castle Scenarios',
            // 'As You Wish Green Company',
            // 'Princess Curators',
            // 'Roads Pro Planopolis',
            // 'Exceptional Collective',
            // 'Andromeda Gals',
            // 'Wedding Organization',
            // 'Big E My Day',
            // 'Sculpted Charming Functions',
            // 'Memories Happening Forest',
            // 'Jade Concourse Celebration',
            // 'Dazzling Guardians',
            // 'Glowing Happen',
            // 'Blowout Coasters',
            // 'Staging By Design',
            // 'The Beginnings',
            // 'Perfect Specacular Paradise',
            // 'Fête Season Living',
            // 'Staging By Design',
            // 'Heavenly Prep',
            // 'Seven Thinking Festivities',
            // 'Roads Black Eventualities',
            // 'Lively Fêtes',
            // 'Revelation Events',
            // 'Paradise Eventalist',
            // 'Run Black Entertainment',
            // 'Living Made Division',
            // 'Seven Thinking Festivities',
            // 'Celebrate The Happen',
            // 'Heavenly Silver Coasters',
            // 'Showtime Gold Lucky',
            // 'Perfect Specacular Paradise',
            // 'Organically Social Memories',
            // 'Festive Supreme',
            // 'Eventurist Hot Organization',
            // 'Memories Savvy Everything',
            // 'Perfect Specacular Paradise',
            // 'Dreams Success Details',
            // 'Spice of Life All Savers',
            // 'Roads In Ranch',
            // 'Roads On The Go',
            // 'Organically Main Memories',
            // 'Vox Scene Bliss',
            // 'Sweet Entertainment',
            // 'Open Sherpas',
            // 'Creative Couture Décor',
            // 'Meeting Tree',
            // 'Eventage Black Events',
            // 'Memories Happening Events',
            // 'Organization House',
            // 'Six Celebrations',
            // 'Orion Guys',
            // 'Elegant Plantopia',
            // 'Planeria Mania',
            // 'Blowout Coasters',
            // 'Organization Science',
            // 'Spring Moments',
            // 'Castle Scenarios',
            // 'Four Event',
            // 'Meeting Attainment',
            // 'Cirque Living',
            // 'Roads Planet',
            // 'Four Parade Circumstances',
            // 'Lucky Surge Inc',
            // 'Prince Hand',
            // 'Encore Guides',
            // 'Millinario Fusion Poppers',
            // 'Checklist On The Go',
            // 'The Evermore',
            // 'Four Production Weddings',
            // 'The Wedding House',
            // 'Classic Season',
            // 'Shindig Red Intercourse',
            // 'Nine Big MomentIntercourse',
            // 'Big PlannersIntercourse',
            // 'Sweet Get ShowsIntercourse',
            // 'Eventage MemoriesIntercourse',
            // 'Classic SeasonIntercourse',
            // 'Diamond ManiaIntercourse',
            // 'Occasions LivingIntercourse',
            // 'Planeria CornerIntercourse',
            // 'Charm CreativeIntercourse',
            // 'Ever FêtesIntercourse',
            // 'Social Of TogetherIntercourse',
            // 'Sage Silver SpringIntercourse',
            // 'Duke TimesIntercourse',
            // 'Divine ScenesIntercourse',
            // 'Eventions SpringIntercourse',
            // 'Glowing HappenIntercourse',
            // 'Events And DécorIntercourse',
            // 'Mannerism CornerIntercourse',
            // 'Land Parade NowIntercourse',
            // 'Sparkling SocialsIntercourse',
            // 'Nth CreativeIntercourse',
            // 'Blowout CoastersIntercourse',
            // 'Matrix Lucky HandIntercourse',
            // 'Everything It GuysIntercourse',
            // 'Fête FunctionsIntercourse',
            // 'Nth EventIntercourse',
            // 'Bonfire ManiaIntercourse',
            // 'Pearl LivingIntercourse',
            // 'Sweet Get ShowsIntercourse',
            // 'Ginger NightIntercourse',
            // 'Show ForestIntercourse',
            // 'Blowout CoastersIntercourse',
            // 'Sparkling SocialsIntercourse',
            // 'Checklist TimeIntercourse',
            // 'X Red DécorIntercourse',
            // 'Create ShindiggerIntercourse',
            // 'Meeting TreeIntercourse',
            // 'Classy EvermoreIntercourse',
            // 'Mannerism Of TrueIntercourse',
            // 'Nine ParadiseIntercourse',
            // 'Special TrueIntercourse',
            // 'Bonfire Hot SeasonIntercourse',
            // 'Roads PlanetIntercourse',
            // 'Glamorous LogicIntercourse',
            // 'Land PrepIntercourse',
            // 'Divine MeetingsIntercourse',
            // 'Andromeda ScenesIntercourse',
            // 'Fab CoastersIntercourse',
            // 'Organic TeamIntercourse',
            // 'Sweet PlanningIntercourse',
            // 'Five Up GroupIntercourse',
            // 'Step CircumstancesIntercourse',
            // 'Step PerfectionIntercourse',
            // 'Simply SweetIntercourse',
            // 'Glamorous LogicIntercourse',
            // 'Shindig Red Intercourse',
            // 'Sparkling Corner',
            // 'Reason Intercourse Poppers',
            // 'Enchanting Factor',
            // 'Castle Jumping Prep',
            // 'Proteus Occasions',
            // 'Organic Savers',
            // 'Heavenly Soiree',
            // 'Little Right Events',
            // 'Sculpted Charming Functions',
            // 'Kinetic Design',
            // 'The Wedding Pro Supreme',
            // 'Prince Specacular Events',
            // 'Checklist Gurus',
            // 'Famous Red Planners',
            // 'Celebration Weddings',
            // 'Organization Pro True',
            // 'Amalgamated On The Go',
            // 'Sparkling Shows',
            // 'Sweet Get Shows',
            // 'Checklist Of Planet',
            // 'Blowout Party Logic',
            // 'Celebration Blowout',
            // 'Proteus Occasions',
            // 'Brilliant Evermore',
            // 'Entertainment Your Sweet',
            // 'Jade Planning Shows',
            // 'Knox Everything',
            // 'Festive Good Corner',
            // 'Festive Flying Planning',
            // 'Crystal Beginnings',
            // 'Princess Now',
            // 'Everything Season',
            // 'Poppins Organizers',
            // 'The Wedding Time Connection',
            // 'Perfect Silver Inc',
            // 'Oui Green Evermore',
            // 'Party Savers',
            // 'Hella True',
            // 'Organic Savers',
            // 'Castle Ranch',
            // 'Everything Get Science',
            // 'Cirque Bird',
            // 'Oh How Running Services',
            // 'Viva Sweet',
            // 'Diamond Outcomes',
            // 'PlanIt It Experimenters',
            // 'Crafty Your Moments',
            // 'Tradecraft Perfection',
            // 'Star Eventments',
            // 'Prince Specacular Events',
            // 'Spice of Life Main Division',
            // 'Manage Success Star',
            // 'Organic Mania',
            // 'Planeria Party Organization',
            // 'Celebrate Enchantment',
            // 'Amalgamated Scenarios',
            // 'Real Social True',
            // 'Seize The Day Living',
            // 'Nth Event',
            // 'Satori Couture Sweet',
            // 'Occasion Blowout',
            // 'Nine Details',
            // 'Associated Pro Gurus',
            // 'Celebrate Your Guardians',
            // 'Oui Group',
            // 'Sunset Good Logic',
            // 'Knox Gals',
            // 'StarStruck Beginnings',
            // 'Open Savers',
            // 'Gold Functions',
            // 'Pearl Party Division',
            // 'Pearl Delight',
            // 'Special Production Company',
            // 'Gold Corner',
            // 'Festive Events',
            // 'Beyond Red Events',
            // 'Revelation Of Factor',
            // 'Occasions Couture Prep',
            // 'Adorn Eventalist',
            // 'Bonfire Green Ranch',
            // 'Ovation Entertainment',
            // 'Oui Red Guys',
            // 'Duchess Prep',
            // 'Strategic Come Attainment',
            // 'Eventions True',
            // 'Nth Creative',
            // 'Little Details',
            // 'Open Jumping Corner',
            // 'Seven Party Curators',
            // 'Special Dream Creative',
            // 'Perfect Happening Night',
            // 'Oh How Scenarios',
            // 'Seize The Day Group',
            // 'As You Wish New Eventualities',
            // 'Alpha Blowout',
            // 'Real Company',
            // 'Events Dream Season',
            // 'Brilliant Gals',
            // 'Jade Planning Shows'
        ];
    }
}
